/* KLCN021 - Database generated from the design class diagram.
   Run in SQL Server Management Studio. Existing tables are preserved. */
IF DB_ID(N'KLCN021_HealthBeauty') IS NULL
    CREATE DATABASE [KLCN021_HealthBeauty];
GO
USE [KLCN021_HealthBeauty];
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.VAITRO',N'U') IS NULL
CREATE TABLE dbo.VAITRO (
    VaiTroID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_VAITRO PRIMARY KEY,
    TenVaiTro nvarchar(50) NOT NULL,
    MoTa nvarchar(255) NULL
);
IF OBJECT_ID(N'dbo.TAIKHOAN',N'U') IS NULL
CREATE TABLE dbo.TAIKHOAN (
    TaiKhoanID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_TAIKHOAN PRIMARY KEY,
    VaiTroID int NOT NULL,
    TenTaiKhoan nvarchar(100) NULL,
    MatKhauHash varchar(255) NOT NULL,
    Email varchar(255) NOT NULL CONSTRAINT UQ_TAIKHOAN_Email UNIQUE,
    TrangThai bit NOT NULL CONSTRAINT DF_TAIKHOAN_TrangThai DEFAULT 1,
    NgayTao datetime2(0) NOT NULL CONSTRAINT DF_TAIKHOAN_NgayTao DEFAULT SYSDATETIME(),
    CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (VaiTroID) REFERENCES dbo.VAITRO(VaiTroID)
);

/* Authentication, detailed authorization and security auditing */
IF COL_LENGTH(N'dbo.TAIKHOAN', N'SoLanDangNhapSai') IS NULL
    ALTER TABLE dbo.TAIKHOAN ADD SoLanDangNhapSai int NOT NULL CONSTRAINT DF_TAIKHOAN_SoLanSai DEFAULT 0;
IF COL_LENGTH(N'dbo.TAIKHOAN', N'KhoaDen') IS NULL
    ALTER TABLE dbo.TAIKHOAN ADD KhoaDen datetime2(0) NULL;
IF COL_LENGTH(N'dbo.TAIKHOAN', N'LanDangNhapCuoi') IS NULL
    ALTER TABLE dbo.TAIKHOAN ADD LanDangNhapCuoi datetime2(0) NULL;

IF OBJECT_ID(N'dbo.QUYEN',N'U') IS NULL
CREATE TABLE dbo.QUYEN (
    QuyenID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_QUYEN PRIMARY KEY,
    MaQuyen varchar(100) NOT NULL CONSTRAINT UQ_QUYEN_Ma UNIQUE,
    TenQuyen nvarchar(150) NOT NULL,
    NhomQuyen varchar(50) NOT NULL,
    MoTa nvarchar(500) NULL,
    TrangThai bit NOT NULL CONSTRAINT DF_QUYEN_TrangThai DEFAULT 1
);
IF OBJECT_ID(N'dbo.VAITRO_QUYEN',N'U') IS NULL
CREATE TABLE dbo.VAITRO_QUYEN (
    VaiTroID int NOT NULL,
    QuyenID int NOT NULL,
    DuocCap bit NOT NULL CONSTRAINT DF_VAITROQUYEN_DuocCap DEFAULT 1,
    NgayGan datetime2(0) NOT NULL CONSTRAINT DF_VAITROQUYEN_NgayGan DEFAULT SYSDATETIME(),
    CONSTRAINT PK_VAITRO_QUYEN PRIMARY KEY (VaiTroID, QuyenID),
    CONSTRAINT FK_VAITROQUYEN_VAITRO FOREIGN KEY (VaiTroID) REFERENCES dbo.VAITRO(VaiTroID),
    CONSTRAINT FK_VAITROQUYEN_QUYEN FOREIGN KEY (QuyenID) REFERENCES dbo.QUYEN(QuyenID)
);
IF OBJECT_ID(N'dbo.REFRESHTOKEN',N'U') IS NULL
CREATE TABLE dbo.REFRESHTOKEN (
    RefreshTokenID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_REFRESHTOKEN PRIMARY KEY,
    TaiKhoanID int NOT NULL,
    TokenHash varchar(255) NOT NULL CONSTRAINT UQ_REFRESHTOKEN_Hash UNIQUE,
    ExpiresAt datetime2(0) NOT NULL,
    CreatedAt datetime2(0) NOT NULL CONSTRAINT DF_REFRESHTOKEN_Created DEFAULT SYSDATETIME(),
    RevokedAt datetime2(0) NULL,
    ReplacedByTokenHash varchar(255) NULL,
    CreatedByIp varchar(45) NULL,
    RevokedByIp varchar(45) NULL,
    CONSTRAINT FK_REFRESHTOKEN_TAIKHOAN FOREIGN KEY (TaiKhoanID) REFERENCES dbo.TAIKHOAN(TaiKhoanID),
    CONSTRAINT CK_REFRESHTOKEN_Expiry CHECK (ExpiresAt > CreatedAt)
);
IF OBJECT_ID(N'dbo.EXTERNALLOGIN',N'U') IS NULL
CREATE TABLE dbo.EXTERNALLOGIN (
    ExternalLoginID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_EXTERNALLOGIN PRIMARY KEY,
    TaiKhoanID int NOT NULL,
    Provider varchar(30) NOT NULL,
    ProviderUserID varchar(255) NOT NULL,
    Email varchar(255) NULL,
    CreatedAt datetime2(0) NOT NULL CONSTRAINT DF_EXTERNALLOGIN_Created DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_EXTERNALLOGIN_ProviderUser UNIQUE (Provider, ProviderUserID),
    CONSTRAINT FK_EXTERNALLOGIN_TAIKHOAN FOREIGN KEY (TaiKhoanID) REFERENCES dbo.TAIKHOAN(TaiKhoanID)
);
IF OBJECT_ID(N'dbo.DANGNHAPLOG',N'U') IS NULL
CREATE TABLE dbo.DANGNHAPLOG (
    DangNhapLogID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_DANGNHAPLOG PRIMARY KEY,
    TaiKhoanID int NULL,
    Email varchar(255) NULL,
    ThanhCong bit NOT NULL,
    LyDoThatBai varchar(100) NULL,
    IpAddress varchar(45) NULL,
    UserAgent nvarchar(500) NULL,
    CreatedAt datetime2(0) NOT NULL CONSTRAINT DF_DANGNHAPLOG_Created DEFAULT SYSDATETIME(),
    CONSTRAINT FK_DANGNHAPLOG_TAIKHOAN FOREIGN KEY (TaiKhoanID) REFERENCES dbo.TAIKHOAN(TaiKhoanID)
);
IF OBJECT_ID(N'dbo.AUDITLOG',N'U') IS NULL
CREATE TABLE dbo.AUDITLOG (
    AuditLogID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_AUDITLOG PRIMARY KEY,
    TaiKhoanID int NULL,
    ActionName varchar(100) NOT NULL,
    EntityName varchar(100) NULL,
    EntityID varchar(100) NULL,
    OldValues nvarchar(max) NULL,
    NewValues nvarchar(max) NULL,
    IpAddress varchar(45) NULL,
    UserAgent nvarchar(500) NULL,
    CreatedAt datetime2(0) NOT NULL CONSTRAINT DF_AUDITLOG_Created DEFAULT SYSDATETIME(),
    CONSTRAINT FK_AUDITLOG_TAIKHOAN FOREIGN KEY (TaiKhoanID) REFERENCES dbo.TAIKHOAN(TaiKhoanID)
);
GO

IF NOT EXISTS (SELECT 1 FROM dbo.QUYEN WHERE MaQuyen = 'ACCOUNT.READ')
    INSERT dbo.QUYEN (MaQuyen,TenQuyen,NhomQuyen,MoTa) VALUES
    ('ACCOUNT.READ',N'Xem tài khoản','ACCOUNT',N'Xem thông tin tài khoản'),
    ('ACCOUNT.WRITE',N'Quản lý tài khoản','ACCOUNT',N'Tạo và cập nhật tài khoản'),
    ('ROLE.READ',N'Xem vai trò và quyền','AUTHORIZATION',N'Tra cứu vai trò, quyền'),
    ('ROLE.WRITE',N'Quản lý vai trò và quyền','AUTHORIZATION',N'Gán hoặc thu hồi quyền'),
    ('CUSTOMER.READ',N'Xem khách hàng','CUSTOMER',N'Tra cứu hồ sơ khách hàng'),
    ('CUSTOMER.WRITE',N'Quản lý khách hàng','CUSTOMER',N'Tạo, sửa hồ sơ khách hàng'),
    ('STAFF.READ',N'Xem nhân viên','STAFF',N'Tra cứu nhân viên'),
    ('STAFF.WRITE',N'Quản lý nhân viên','STAFF',N'Tạo, sửa, khóa nhân viên'),
    ('SERVICE.READ',N'Xem dịch vụ','SERVICE',N'Tra cứu dịch vụ và combo'),
    ('SERVICE.WRITE',N'Quản lý dịch vụ','SERVICE',N'Tạo, sửa, ngừng dịch vụ'),
    ('APPOINTMENT.READ',N'Xem lịch hẹn','APPOINTMENT',N'Tra cứu lịch hẹn'),
    ('APPOINTMENT.WRITE',N'Quản lý lịch hẹn','APPOINTMENT',N'Tạo, sửa, phân công, hủy lịch'),
    ('INVOICE.READ',N'Xem hóa đơn','BILLING',N'Tra cứu hóa đơn'),
    ('INVOICE.WRITE',N'Quản lý hóa đơn','BILLING',N'Lập và cập nhật hóa đơn'),
    ('PAYMENT.WRITE',N'Xử lý thanh toán','BILLING',N'Ghi nhận, xác nhận, hủy thanh toán'),
    ('PROMOTION.WRITE',N'Quản lý khuyến mãi','PROMOTION',N'Quản lý chương trình và voucher'),
    ('REVIEW.MODERATE',N'Duyệt đánh giá','REVIEW',N'Duyệt, ẩn hoặc xóa đánh giá'),
    ('REPORT.READ',N'Xem báo cáo','REPORT',N'Xem và xuất báo cáo');
GO

CREATE INDEX IX_REFRESHTOKEN_Account ON dbo.REFRESHTOKEN(TaiKhoanID, RevokedAt, ExpiresAt);
CREATE INDEX IX_DANGNHAPLOG_EmailTime ON dbo.DANGNHAPLOG(Email, CreatedAt);
CREATE INDEX IX_AUDITLOG_AccountTime ON dbo.AUDITLOG(TaiKhoanID, CreatedAt);
GO
IF OBJECT_ID(N'dbo.KHACHHANG',N'U') IS NULL
CREATE TABLE dbo.KHACHHANG (
    KhachHangID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_KHACHHANG PRIMARY KEY,
    TaiKhoanID int NULL CONSTRAINT UQ_KHACHHANG_TaiKhoan UNIQUE,
    HoTen nvarchar(100) NOT NULL, SoDienThoai varchar(15) NULL,
    GioiTinh nvarchar(20) NULL, DiemThuong int NOT NULL CONSTRAINT DF_KHACHHANG_Diem DEFAULT 0,
    CONSTRAINT FK_KHACHHANG_TAIKHOAN FOREIGN KEY (TaiKhoanID) REFERENCES dbo.TAIKHOAN(TaiKhoanID)
);
IF OBJECT_ID(N'dbo.NHANVIEN',N'U') IS NULL
CREATE TABLE dbo.NHANVIEN (
    NhanVienID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_NHANVIEN PRIMARY KEY,
    TaiKhoanID int NULL CONSTRAINT UQ_NHANVIEN_TaiKhoan UNIQUE,
    HoTen nvarchar(100) NOT NULL, ChucVu nvarchar(50) NULL, ChuyenMon nvarchar(255) NULL,
    SoDienThoai varchar(15) NULL, NgayVaoLam date NULL,
    CONSTRAINT FK_NHANVIEN_TAIKHOAN FOREIGN KEY (TaiKhoanID) REFERENCES dbo.TAIKHOAN(TaiKhoanID)
);
IF OBJECT_ID(N'dbo.LICHLAMVIEC',N'U') IS NULL
CREATE TABLE dbo.LICHLAMVIEC (
    LichLamViecID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_LICHLAMVIEC PRIMARY KEY,
    NhanVienID int NOT NULL, NgayLam date NOT NULL, GioBatDau time(0) NOT NULL, GioKetThuc time(0) NOT NULL,
    TrangThai nvarchar(30) NULL,
    CONSTRAINT FK_LICHLAMVIEC_NHANVIEN FOREIGN KEY (NhanVienID) REFERENCES dbo.NHANVIEN(NhanVienID),
    CONSTRAINT CK_LICHLAMVIEC_Gio CHECK (GioKetThuc > GioBatDau)
);
IF OBJECT_ID(N'dbo.LOAIDICHVU',N'U') IS NULL
CREATE TABLE dbo.LOAIDICHVU (
    LoaiDichVuID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_LOAIDICHVU PRIMARY KEY,
    TenLoai nvarchar(100) NOT NULL, MoTa nvarchar(255) NULL, TrangThai bit NOT NULL DEFAULT 1
);
IF OBJECT_ID(N'dbo.DICHVU',N'U') IS NULL
CREATE TABLE dbo.DICHVU (
    DichVuID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_DICHVU PRIMARY KEY,
    LoaiDichVuID int NOT NULL, TenDichVu nvarchar(150) NOT NULL, Gia decimal(18,2) NOT NULL,
    ThoiLuongPhut int NOT NULL, MoTa nvarchar(1000) NULL, TrangThai bit NOT NULL DEFAULT 1,
    CONSTRAINT FK_DICHVU_LOAI FOREIGN KEY (LoaiDichVuID) REFERENCES dbo.LOAIDICHVU(LoaiDichVuID),
    CONSTRAINT CK_DICHVU_Gia CHECK (Gia >= 0), CONSTRAINT CK_DICHVU_ThoiLuong CHECK (ThoiLuongPhut > 0)
);
IF OBJECT_ID(N'dbo.COMBODICHVU',N'U') IS NULL
CREATE TABLE dbo.COMBODICHVU (
    ComboID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_COMBODICHVU PRIMARY KEY,
    TenCombo nvarchar(150) NOT NULL, GiaCombo decimal(18,2) NOT NULL,
    NgayBatDauHieuLuc date NULL, NgayKetThucHieuLuc date NULL, TrangThai bit NOT NULL DEFAULT 1,
    CONSTRAINT CK_COMBO_Gia CHECK (GiaCombo >= 0),
    CONSTRAINT CK_COMBO_Ngay CHECK (NgayKetThucHieuLuc IS NULL OR NgayBatDauHieuLuc IS NULL OR NgayKetThucHieuLuc >= NgayBatDauHieuLuc)
);
IF OBJECT_ID(N'dbo.CHITIETCOMBO',N'U') IS NULL
CREATE TABLE dbo.CHITIETCOMBO (
    ComboChiTietID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_CHITIETCOMBO PRIMARY KEY,
    ComboID int NOT NULL, DichVuID int NOT NULL, SoLuong int NOT NULL DEFAULT 1,
    CONSTRAINT UQ_CHITIETCOMBO UNIQUE (ComboID,DichVuID),
    CONSTRAINT FK_CTCOMBO_COMBO FOREIGN KEY (ComboID) REFERENCES dbo.COMBODICHVU(ComboID),
    CONSTRAINT FK_CTCOMBO_DICHVU FOREIGN KEY (DichVuID) REFERENCES dbo.DICHVU(DichVuID),
    CONSTRAINT CK_CTCOMBO_SoLuong CHECK (SoLuong > 0)
);
IF OBJECT_ID(N'dbo.LICHHEN',N'U') IS NULL
CREATE TABLE dbo.LICHHEN (
    LichHenID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_LICHHEN PRIMARY KEY,
    KhachHangID int NOT NULL, NhanVienID int NULL, NgayGioHen datetime2(0) NOT NULL,
    GioKetThucDuKien time(0) NULL, TrangThai nvarchar(30) NOT NULL DEFAULT N'ChoXacNhan', GhiChu nvarchar(1000) NULL,
    CONSTRAINT FK_LICHHEN_KHACH FOREIGN KEY (KhachHangID) REFERENCES dbo.KHACHHANG(KhachHangID),
    CONSTRAINT FK_LICHHEN_NHANVIEN FOREIGN KEY (NhanVienID) REFERENCES dbo.NHANVIEN(NhanVienID)
);
IF OBJECT_ID(N'dbo.CHITIETLICHHEN',N'U') IS NULL
CREATE TABLE dbo.CHITIETLICHHEN (
    ChiTietLichHenID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_CHITIETLICHHEN PRIMARY KEY,
    LichHenID int NOT NULL, DichVuID int NOT NULL, ComboID int NULL,
    ThoiLuongThucTe int NULL, GiaDuKien decimal(18,2) NOT NULL,
    CONSTRAINT FK_CTLICH_LICHHEN FOREIGN KEY (LichHenID) REFERENCES dbo.LICHHEN(LichHenID),
    CONSTRAINT FK_CTLICH_DICHVU FOREIGN KEY (DichVuID) REFERENCES dbo.DICHVU(DichVuID),
    CONSTRAINT FK_CTLICH_COMBO FOREIGN KEY (ComboID) REFERENCES dbo.COMBODICHVU(ComboID)
);
IF OBJECT_ID(N'dbo.KHUYENMAI',N'U') IS NULL
CREATE TABLE dbo.KHUYENMAI (
    KhuyenMaiID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_KHUYENMAI PRIMARY KEY,
    TenKhuyenMai nvarchar(150) NOT NULL, LoaiGiam nvarchar(30) NOT NULL, MucGiam decimal(18,2) NOT NULL,
    DieuKienApDung nvarchar(1000) NULL, NgayBatDauHieuLuc datetime2(0) NULL, NgayKetThucHieuLuc datetime2(0) NULL,
    CONSTRAINT CK_KM_MucGiam CHECK (MucGiam >= 0)
);
IF OBJECT_ID(N'dbo.VOUCHER',N'U') IS NULL
CREATE TABLE dbo.VOUCHER (
    VoucherID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_VOUCHER PRIMARY KEY,
    MaCode varchar(30) NOT NULL CONSTRAINT UQ_VOUCHER_MaCode UNIQUE, KhuyenMaiID int NOT NULL, KhachHangID int NULL,
    GiaTriGiam decimal(18,2) NOT NULL, HanSuDung datetime2(0) NOT NULL, TrangThai bit NOT NULL DEFAULT 1,
    CONSTRAINT FK_VOUCHER_KM FOREIGN KEY (KhuyenMaiID) REFERENCES dbo.KHUYENMAI(KhuyenMaiID),
    CONSTRAINT FK_VOUCHER_KHACH FOREIGN KEY (KhachHangID) REFERENCES dbo.KHACHHANG(KhachHangID)
);
IF OBJECT_ID(N'dbo.HOADON',N'U') IS NULL
CREATE TABLE dbo.HOADON (
    HoaDonID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_HOADON PRIMARY KEY,
    LichHenID int NOT NULL, KhachHangID int NOT NULL, NgayLap datetime2(0) NOT NULL DEFAULT SYSDATETIME(),
    TongTienTruocGiam decimal(18,2) NOT NULL DEFAULT 0, TongTienSauGiam decimal(18,2) NOT NULL DEFAULT 0,
    TrangThai nvarchar(30) NOT NULL DEFAULT N'ChuaThanhToan',
    CONSTRAINT FK_HOADON_LICHHEN FOREIGN KEY (LichHenID) REFERENCES dbo.LICHHEN(LichHenID),
    CONSTRAINT FK_HOADON_KHACH FOREIGN KEY (KhachHangID) REFERENCES dbo.KHACHHANG(KhachHangID)
);
IF OBJECT_ID(N'dbo.CHITIETHOADON',N'U') IS NULL
CREATE TABLE dbo.CHITIETHOADON (
    HoaDonChiTietID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_CHITIETHOADON PRIMARY KEY,
    HoaDonID int NOT NULL, DichVuID int NULL, ComboID int NULL, SoLuong int NOT NULL DEFAULT 1, DonGia decimal(18,2) NOT NULL,
    CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (HoaDonID) REFERENCES dbo.HOADON(HoaDonID),
    CONSTRAINT FK_CTHD_DICHVU FOREIGN KEY (DichVuID) REFERENCES dbo.DICHVU(DichVuID),
    CONSTRAINT FK_CTHD_COMBO FOREIGN KEY (ComboID) REFERENCES dbo.COMBODICHVU(ComboID),
    CONSTRAINT CK_CTHD_MotLoai CHECK ((DichVuID IS NOT NULL AND ComboID IS NULL) OR (DichVuID IS NULL AND ComboID IS NOT NULL))
);
IF OBJECT_ID(N'dbo.THANHTOAN',N'U') IS NULL
CREATE TABLE dbo.THANHTOAN (
    ThanhToanID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_THANHTOAN PRIMARY KEY,
    HoaDonID int NOT NULL, PhuongThuc nvarchar(30) NOT NULL, SoTien decimal(18,2) NOT NULL,
    NgayGioThanhToan datetime2(0) NULL, TrangThai nvarchar(30) NOT NULL DEFAULT N'ChoXuLy',
    CONSTRAINT FK_THANHTOAN_HOADON FOREIGN KEY (HoaDonID) REFERENCES dbo.HOADON(HoaDonID), CONSTRAINT CK_TT_SoTien CHECK (SoTien > 0)
);
IF OBJECT_ID(N'dbo.DANHGIA',N'U') IS NULL
CREATE TABLE dbo.DANHGIA (
    DanhGiaID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_DANHGIA PRIMARY KEY,
    HoaDonID int NOT NULL, SoSao tinyint NOT NULL, BinhLuan nvarchar(1000) NULL, NgayDanhGia datetime2(0) NOT NULL DEFAULT SYSDATETIME(), TrangThai nvarchar(30) NOT NULL DEFAULT N'ChoDuyet',
    CONSTRAINT FK_DANHGIA_HOADON FOREIGN KEY (HoaDonID) REFERENCES dbo.HOADON(HoaDonID), CONSTRAINT CK_DG_SoSao CHECK (SoSao BETWEEN 1 AND 5)
);
IF OBJECT_ID(N'dbo.GIAODICHDIEM',N'U') IS NULL
CREATE TABLE dbo.GIAODICHDIEM (
    GiaoDichID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_GIAODICHDIEM PRIMARY KEY,
    KhachHangID int NOT NULL, HoaDonID int NULL, SoDiem int NOT NULL, LoaiGiaoDich nvarchar(20) NOT NULL,
    NgayGiaoDich datetime2(0) NOT NULL DEFAULT SYSDATETIME(), GhiChu nvarchar(500) NULL,
    CONSTRAINT FK_GD_DIEM_KHACH FOREIGN KEY (KhachHangID) REFERENCES dbo.KHACHHANG(KhachHangID),
    CONSTRAINT FK_GD_DIEM_HOADON FOREIGN KEY (HoaDonID) REFERENCES dbo.HOADON(HoaDonID)
);
GO

CREATE INDEX IX_LICHHEN_NgayGio ON dbo.LICHHEN(NgayGioHen,TrangThai);
CREATE INDEX IX_HOADON_NgayLap ON dbo.HOADON(NgayLap,TrangThai);
CREATE INDEX IX_DICHVU_Loai ON dbo.DICHVU(LoaiDichVuID,TrangThai);
CREATE INDEX IX_GD_DIEM_Khach ON dbo.GIAODICHDIEM(KhachHangID,NgayGiaoDich);
GO
